# Generated by Django 2.0.5 on 2018-06-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Deafault Name', max_length=50),
            preserve_default=False,
        ),
    ]
