# Generated by Django 2.0.5 on 2018-07-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='active',
            new_name='is_active',
        ),
    ]
