# Generated by Django 2.0.5 on 2018-05-26 09:02

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180526_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=product.models.image_path_name),
        ),
    ]
