# Generated by Django 2.0.5 on 2018-06-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectviewed',
            old_name='id_address',
            new_name='ip_address',
        ),
    ]
