# Generated by Django 2.0.5 on 2018-05-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
