# Generated by Django 2.0.5 on 2018-05-28 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180528_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='time_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
